# Site settings

title: 
email: mnooranidoost@fsu.edu

description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
scholar_username: citations?user=PWU2CdgAAAAJ&hl=en
github_username:  mnooranidoost

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Postdoctoral Scholar"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
